
# removing some cards with extreame pre reqs like 1 mil invested for BOA.  
travel_cards = [
    #{"Travel CB": 5.55, "Travel Types": "Most Travel", "Spend Cap": "$500/ month", "Bank Name": "Citi", "Card Name": "Custom Cash", "Type": "MC", "SUB": 200, "FTF": 3, "Travel Benefits": "None", "Membership": "Open, req. Rewards+ card [A]"},
    #{"Travel CB": 5.25, "Travel Types": "Most Travel", "Spend Cap": "$2,500/ quarter", "Bank Name": "Bank of America", "Card Name": "Customized Cash", "Type": "Visa", "SUB": 200, "FTF": 3, "Travel Benefits": "None", "Membership": "Open, req. $100k [B]"},
    {"Travel CB": 5, "Travel Types": "Airfare, Hotels", "Spend Cap": "No Cap", "Bank Name": "GreenState CU", "Card Name": "World Mastercard", "Type": "MC", "SUB": 100, "FTF": 0, "Travel Benefits": "Car Rental CDW", "Membership": "Am. Cons. Counc., $5 [C]"},
    {"Travel CB": 5, "Travel Types": "Prepaid Portal Only", "Spend Cap": "No Cap", "Bank Name": "Chase", "Card Name": "Freedom Flex", "Type": "MC", "SUB": 200, "FTF": 3, "Travel Benefits": "Car Rental CDW; Trip Cancell./ Interrup. Insurance", "Membership": "Open"},
    {"Travel CB": 5, "Travel Types": "Prepaid Portal Only", "Spend Cap": "No Cap", "Bank Name": "Chase", "Card Name": "Freedom Unlimited", "Type": "Visa", "SUB": 200, "FTF": 3, "Travel Benefits": "Car Rental CDW; Trip Cancell./ Interrup. Insurance", "Membership": "Open"},
    {"Travel CB": 5, "Travel Types": "Ground Transp. plus Prepaid Portal", "Spend Cap": "$2,000/ quarter (No Cap for Portal)", "Bank Name": "U.S. Bank", "Card Name": "Cash+", "Type": "Visa", "SUB": 200, "FTF": 3, "Travel Benefits": "None", "Membership": "Open"},
    {"Travel CB": 5, "Travel Types": "Prepaid Portal Only", "Spend Cap": "No Cap", "Bank Name": "U.S. Bank (Elan)", "Card Name": "Max Cash Preferred", "Type": "Visa/MC", "SUB": 150, "FTF": 3, "Travel Benefits": "None", "Membership": "Open"},
    {"Travel CB": 5, "Travel Types": "Most Travel", "Spend Cap": "$500/ month", "Bank Name": "Citi", "Card Name": "Custom Cash", "Type": "MC", "SUB": 200, "FTF": 3, "Travel Benefits": "None", "Membership": "Open"},
    #{"Travel CB": 4.5, "Travel Types": "Most Travel", "Spend Cap": "$2,500/ quarter", "Bank Name": "Bank of America", "Card Name": "Customized Cash", "Type": "Visa", "SUB": 200, "FTF": 3, "Travel Benefits": "None", "Membership": "Open, req. $50k [B]"},
    {"Travel CB": 4, "Travel Types": "Most Travel", "Spend Cap": "$7,000/ quarter", "Bank Name": "Huntington", "Card Name": "Voice Business", "Type": "MC", "SUB": 0, "FTF": 0, "Travel Benefits": "None", "Membership": "7 States [D]"},
    #{"Travel CB": 3.75, "Travel Types": "Most Travel", "Spend Cap": "$2,500/ quarter", "Bank Name": "Bank of America", "Card Name": "Customized Cash", "Type": "Visa", "SUB": 200, "FTF": 3, "Travel Benefits": "None", "Membership": "Open, req. $20k [B]"},
    #{"Travel CB": 3.4, "Travel Types": "Most Travel + Global Entry", "Spend Cap": "No Cap", "Bank Name": "PenFed", "Card Name": "Pathfinder Rewards", "Type": "Visa", "SUB": 425, "FTF": 0, "Travel Benefits": "Baggage Loss/Delay Insurance, Travel Accident Insurance, Trip Cancell./ Interrup. Insurance", "Membership": "$5, req. checking and $500 or direct deposit [E]"},
    {"Travel CB": 3, "Travel Types": "Most Travel", "Spend Cap": "No Cap", "Bank Name": "Wells Fargo", "Card Name": "Autograph", "Type": "Visa", "SUB": 200, "FTF": 0, "Travel Benefits": "Car Rental CDW", "Membership": "Open"},
    {"Travel CB": 3, "Travel Types": "Most Travel", "Spend Cap": "No Cap", "Bank Name": "Comenity", "Card Name": "AAA Travel Advantage", "Type": "Visa", "SUB": 100, "FTF": 0, "Travel Benefits": "None", "Membership": "Open (AAA membership not req.)"},
    {"Travel CB": 3, "Travel Types": "Most Travel", "Spend Cap": "No Cap", "Bank Name": "InFirst FCU", "Card Name": "Visa Rewards", "Type": "Visa", "SUB": 15, "FTF": "Unk.", "Travel Benefits": "Baggage Loss/Delay Insurance, Travel Accident Insurance", "Membership": "Open, $20 [F]"},
    {"Travel CB": 3, "Travel Types": "Most Travel", "Spend Cap": "No Cap", "Bank Name": "FNBO", "Card Name": "Getaway", "Type": "MC", "SUB": 0, "FTF": 0, "Travel Benefits": "None", "Membership": "Open"},
    {"Travel CB": 3, "Travel Types": "Most Travel", "Spend Cap": "No Cap", "Bank Name": "Synchrony", "Card Name": "Venmo Visa", "Type": "Visa", "SUB": 0, "FTF": 0, "Travel Benefits": "None", "Membership": "Venmo"},
    {"Travel CB": 3, "Travel Types": "Most Travel", "Spend Cap": "No Cap", "Bank Name": "Citi", "Card Name": "Costco Anywhere", "Type": "Visa", "SUB": 0, "FTF": 0, "Travel Benefits": "Car Rental CDW, Travel Accident Insurance", "Membership": "Costco, $60+ [G]"},
    {"Travel CB": 3, "Travel Types": "Airfare, Hotels, Car Rentals", "Spend Cap": "No Cap", "Bank Name": "Barclays", "Card Name": "AARP Travel Rewards", "Type": "MC", "SUB": 100, "FTF": 0, "Travel Benefits": "Baggage Loss/Delay Insurance, Car Rental CDW, Travel Accident Insurance, Trip Cancell./ Interrup. Insurance", "Membership": "Open (AARP membership not req.)"},
    {"Travel CB": 3, "Travel Types": "Most Travel + Global Entry", "Spend Cap": "No Cap", "Bank Name": "Summit CU", "Card Name": "Ultimate CashPerks", "Type": "Visa", "SUB": 0, "FTF": 0, "Travel Benefits": "None", "Membership": "Open, $5 [H]"},
    {"Travel CB": 3, "Travel Types": "Most Travel", "Spend Cap": "$2,500/ quarter", "Bank Name": "Bank of America", "Card Name": "Customized Cash", "Type": "Visa", "SUB": 200, "FTF": 3, "Travel Benefits": "None", "Membership": "Open"},
    {"Travel CB": 3, "Travel Types": "Most Travel", "Spend Cap": "$2,000/ quarter", "Bank Name": "Huntington", "Card Name": "Voice Rewards", "Type": "MC", "SUB": 0, "FTF": 0, "Travel Benefits": "None", "Membership": "7 States [I]"},
    
    # Annaul fee cards
    {"Travel CB": 3, "Travel Types": "Most Travel", "Spend Cap": "No Cap", "Bank Name": "AmEx", "Card Name": "AmEx Gold", "Type": "AmEx", "SUB": 900, "FTF": 0, "Travel Benefits": "None", "Membership": "Open", "Annual Fee": 250}
]



dining_data = [
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "MC",
        "Bank Name": "Capital One",
        "Card Name": "SavorOne",
        "SUB": 200,
        "FTF": "No FTF",
        "Other Category": "Y [M]",
        "Membership": "Open"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "Visa/ MC",
        "Bank Name": "Navy FCU",
        "Card Name": "Go Rewards",
        "SUB": 200,
        "FTF": "No FTF",
        "Other Category": "N [N]",
        "Membership": "NFCU, $5 [N]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "Visa",
        "Bank Name": "UMB",
        "Card Name": "Simply Rewards",
        "SUB": 150,
        "FTF": "2%",
        "Other Category": "Y [O]",
        "Membership": "Open"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "Visa",
        "Bank Name": "TD Bank",
        "Card Name": "Cash",
        "SUB": 150,
        "FTF": "3%",
        "Other Category": "N [P]",
        "Membership": "15 States + D.C. [P]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "Visa",
        "Bank Name": "Comenity",
        "Card Name": "AAA Travel Advantage",
        "SUB": 100,
        "FTF": "No FTF",
        "Other Category": "Y [Q]",
        "Membership": "Open (AAA membership not req.)"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "Visa",
        "Bank Name": "Synchrony",
        "Card Name": "Verizon Visa",
        "SUB": 100,
        "FTF": "No FTF",
        "Other Category": "Y [R]",
        "Membership": "Verizon Wireless [R]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "MC",
        "Bank Name": "Cardless",
        "Card Name": "Cavs Card",
        "SUB": 50,
        "FTF": "No FTF",
        "Other Category": "Y [S]",
        "Membership": "Open"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "MC",
        "Bank Name": "Cardless",
        "Card Name": "Celtics Card",
        "SUB": 50,
        "FTF": "No FTF",
        "Other Category": "Y [T]",
        "Membership": "Open"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "MC",
        "Bank Name": "Cardless",
        "Card Name": "Marlins Card",
        "SUB": 50,
        "FTF": "No FTF",
        "Other Category": "Y [U]",
        "Membership": "Open"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "MC",
        "Bank Name": "Cardless",
        "Card Name": "Pelicans Card",
        "SUB": 50,
        "FTF": "No FTF",
        "Other Category": "Y [V]",
        "Membership": "Open"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "MC",
        "Bank Name": "Synchrony",
        "Card Name": "Sam's Club Mastercard",
        "SUB": 30,
        "FTF": "No FTF",
        "Other Category": "Y [W]",
        "Membership": "Sam's Club, $45+ [W]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "AmEx",
        "Bank Name": "USAA",
        "Card Name": "Rewards",
        "SUB": 25,
        "FTF": "No FTF",
        "Other Category": "N [X]",
        "Membership": "USAA [X]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "Visa",
        "Bank Name": "InFirst FCU",
        "Card Name": "Visa Rewards",
        "SUB": 15,
        "FTF": "Unk.",
        "Other Category": "Y [Y]",
        "Membership": "Open, $20 [Y]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "MC",
        "Bank Name": "FNBO",
        "Card Name": "Getaway",
        "SUB": 0,
        "FTF": "No FTF",
        "Other Category": "Y [Z]",
        "Membership": "Open"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "Visa",
        "Bank Name": "Synchrony",
        "Card Name": "Venmo Visa",
        "SUB": 0,
        "FTF": "No FTF",
        "Other Category": "Y [AA]",
        "Membership": "Venmo"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "MC",
        "Bank Name": "Bank of the West",
        "Card Name": "Cash Back World",
        "SUB": 0,
        "FTF": "3%",
        "Other Category": "Y [BB]",
        "Membership": "Open Except D.C."
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "Visa",
        "Bank Name": "Synovus",
        "Card Name": "Cash Rewards",
        "SUB": 0,
        "FTF": "3%",
        "Other Category": "Y [CC]",
        "Membership": "6 States [CC]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "Visa",
        "Bank Name": "Redstone FCU",
        "Card Name": "Rural King Card",
        "SUB": 0,
        "FTF": "No FTF",
        "Other Category": "Y [DD]",
        "Membership": "Open, $5 [DD]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "AmEx",
        "Bank Name": "Navy FCU",
        "Card Name": "More Rewards",
        "SUB": 0,
        "FTF": "No FTF",
        "Other Category": "Y [EE]",
        "Membership": "NFCU, $5 [EE]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "No Cap",
        "Type": "Visa",
        "Bank Name": "Citi",
        "Card Name": "Costco Anywhere",
        "SUB": 0,
        "FTF": "No FTF",
        "Other Category": "Y [FF]",
        "Membership": "Costco, $60+ [FF]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "$2,500/ quarter",
        "Type": "Visa",
        "Bank Name": "Bank of America",
        "Card Name": "Customized Cash",
        "SUB": 200,
        "FTF": "3%",
        "Other Category": "Y [B]",
        "Membership": "Open"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "$8,000/ year",
        "Type": "Visa",
        "Bank Name": "PNC",
        "Card Name": "Cash Rewards",
        "SUB": 200,
        "FTF": "3%",
        "Other Category": "Y [GG]",
        "Membership": "25 States + D.C. [GG]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "$2,000/ quarter",
        "Type": "MC",
        "Bank Name": "Huntington",
        "Card Name": "Voice Rewards",
        "SUB": 0,
        "FTF": "No FTF",
        "Other Category": "Y [HH]",
        "Membership": "7 States [HH]"
    },
    {
        "Dining CB": 3,
        "Spend Cap": "$6,000/ year",
        "Type": "MC",
        "Bank Name": "U.S. Bank",
        "Card Name": "Various Kroger-branded cards",
        "SUB": 100,
        "FTF": "No FTF",
        "Other Category": "Y [C]",
        "Membership": "Open"
    }
]

# this data is not up to date
other_cards = [
    {"CB": 3, "Travel Types": "Most Travel", "Spend Cap": "No Cap", "Bank Name": "Capital One", "Card Name": "Venture X", "Type": "Visa", "SUB": 750, "FTF": 0, "Travel Benefits": "None", "Membership": "Open", "Annual Fee": 395, "Credits": 400},
    
    
    {"CB": 3, "FTF": "No FTF", "Type": "MC", "Bank Name": "Logix FCU", "Card Name": "Platinum Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Am. Cons. Counc., 8 States + D.C., req. $100k [A]"},
    {"CB": 2.625, "FTF": 3, "Type": "Visa", "Bank Name": "Bank of America", "Card Name": "Unlimited Cash Rewards", "SUB": 200, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. $100k [B]"},
    {"CB": 2.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Alliant CU", "Card Name": "Cashback Visa Signature", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Foster Care to Success, $5, req. checking, e-deposit and $1,000 [C]"},
    {"CB": 2.25, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Truist", "Card Name": "Enjoy Cash", "SUB": "No SUB", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "15 States + D.C., req. $100k [D]"},
    {"CB": 2.25, "FTF": 3, "Type": "Visa", "Bank Name": "Bank of America", "Card Name": "Unlimited Cash Rewards", "SUB": 200, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. $50k [B]"},
    {"CB": 2.22, "FTF": 3, "Type": "MC", "Bank Name": "Citi", "Card Name": "Double Cash", "SUB": 200, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. Rewards+ card [E]"},
    {"CB": 2, "FTF": "No FTF", "Type": "Visa", "Bank Name": "State Department FCU", "Card Name": "Premium CashBack+", "SUB": 200, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Am. Cons. Counc., $0 [F]"},
    {"CB": 2, "FTF": "No FTF", "Type": "Visa", "Bank Name": "U.S. Bank (Elan)", "Card Name": "Fidelity Rewards", "SUB": 150, "Car Rental CDW": "N", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "Y", "Membership": "Fidelity, $0 [G]"},
    {"CB": 2, "FTF": "No FTF", "Type": "MC", "Bank Name": "Capital One", "Card Name": "BJ’s One+ Mastercard", "SUB": 40, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "BJ’s, $110 [H]"},
    {"CB": 2, "FTF": "No FTF", "Type": "MC", "Bank Name": "SoFi Bank", "Card Name": "SoFi Credit Card", "SUB": "No SUB", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "Y", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open"},
    {"CB": 2, "FTF": "No FTF", "Type": "AmEx", "Bank Name": "Comenity", "Card Name": "Bread Cashback", "SUB": "Y [I]", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "N", "Cell Prot.": "Y", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open"},
    {"CB": 2, "FTF": "No FTF", "Type": "Visa", "Bank Name": "PenFed CU", "Card Name": "Power Cash Rewards", "SUB": 100, "Car Rental CDW": "N", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "Y", "Membership": "$5, req. checking and $500 or direct deposit [J]"},
    {"CB": 2, "FTF": "No FTF", "Type": "Visa", "Bank Name": "PSECU", "Card Name": "Founder’s Rewards", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Penn. Rec. and Park Soc., $15, req. checking and direct deposit [K]"},
    {"CB": 2, "FTF": "No FTF", "Type": "MC", "Bank Name": "Logix FCU", "Card Name": "Platinum Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Am. Cons. Counc., 8 States + D.C., req. $35k [A]"},
    {"CB": 2, "FTF": "No FTF", "Type": "MC", "Bank Name": "Fifth Third", "Card Name": "Preferred Cash/Back", "SUB": "No SUB", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "Y", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. $100k [L]"},
    {"CB": 2, "FTF": 1, "Type": "Visa", "Bank Name": "Carolinas Telco FCU", "Card Name": "2% Cash Back", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "N. Carolina Cons. Counc., $25 [M]"},
    {"CB": 2, "FTF": "$2.50 [N]", "Type": "MC", "Bank Name": "Dover FCU", "Card Name": "Cash Back", "SUB": "No SUB", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Friends of Bombay Hook, $20 [N]"},
    {"CB": 2, "FTF": "2.70%", "Type": "AmEx", "Bank Name": "American Express", "Card Name": "Blue Business Cash", "SUB": 250, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open"},
    {"CB": 2, "FTF": 3, "Type": "Visa", "Bank Name": "Wells Fargo", "Card Name": "Active Cash", "SUB": 200, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "Y", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open"},
    {"CB": 2, "FTF": 3, "Type": "Visa", "Bank Name": "FNBO", "Card Name": "Evergreen", "SUB": 200, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open"},
    {"CB": 2, "FTF": 3, "Type": "MC", "Bank Name": "Citi", "Card Name": "Double Cash", "SUB": 200, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open"},
    {"CB": 2, "FTF": 3, "Type": "Visa", "Bank Name": "TD Bank", "Card Name": "Double Up", "SUB": 100, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "15 States + D.C., req. checking and $100 [P]"},
    {"CB": 2, "FTF": 3, "Type": "MC", "Bank Name": "Synchrony", "Card Name": "PayPal Cashback", "SUB": "No SUB", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "PayPal, $0 [Q]"},
    {"CB": 2, "FTF": 3, "Type": "MC", "Bank Name": "Synchrony", "Card Name": "Premier", "SUB": "No SUB", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open"},
    {"CB": 2, "FTF": 3, "Type": "MC", "Bank Name": "KeyBank", "Card Name": "Key Cashback", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "15 States, req. checking, e-deposit, savings and $1k [R]"},
    {"CB": 1.9, "FTF": "No FTF", "Type": "MC", "Bank Name": "Citizens", "Card Name": "Cash Back Plus", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Open, req. checking and $5k/month deposits [S]"},
    {"CB": 1.875, "FTF": 3, "Type": "Visa", "Bank Name": "Bank of America", "Card Name": "Unlimited Cash Rewards", "SUB": 200, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. $20k [B]"},
    {"CB": 1.875, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Truist", "Card Name": "Enjoy Cash", "SUB": "No SUB", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "15 States + D.C., req. $25k [D]"},
    {"CB": 1.80, "FTF": "No FTF", "Type": "MC", "Bank Name": "Citizens", "Card Name": "Cash Back Plus", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Open"},
    {"CB": 1.80, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Nuvision FCU", "Card Name": "Visa Signature", "SUB": "No SUB", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, $5 [T]"},
    {"CB": 1.75, "FTF": "No FTF", "Type": "MC", "Bank Name": "Navy FCU", "Card Name": "cashRewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "N", "Cell Prot.": "Y", "Price Prot.": "N", "Bag Delay": "N", "Membership": "NFCU, $5, req. checking and direct deposit [U]"},
    {"CB": 1.75, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Navy FCU", "Card Name": "cashRewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "NFCU, $5, req. checking and direct deposit [U]"},
    {"CB": 1.67, "FTF": "No FTF", "Type": "MC", "Bank Name": "Fifth Third", "Card Name": "Cash/Back", "SUB": "No SUB", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "Y", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. checking [V]"},
    {"CB": 1.67, "FTF": 2, "Type": "Visa", "Bank Name": "UMB", "Card Name": "Direct Cash", "SUB": 166.67, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "8 States, req. checking [W]"},
    {"CB": 1.65, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Truist", "Card Name": "Enjoy Cash", "SUB": "No SUB", "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "15 States + D.C., req. $10k [D]"},
    {"CB": 1.65, "FTF": "No FTF", "Type": "MC", "Bank Name": "TD Bank", "Card Name": "Cash Visa", "SUB": 200, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "N", "Cell Prot.": "Y", "Price Prot.": "N", "Bag Delay": "Y", "Membership": "Open, req. checking and $5k [X]"},
    {"CB": 1.65, "FTF": "No FTF", "Type": "MC", "Bank Name": "TD Bank", "Card Name": "Unsecured", "SUB": 150, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. checking and $5k [X]"},
    {"CB": 1.65, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Golden 1 CU", "Card Name": "Platinum Rewards", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, $8 [Y]"},
    {"CB": 1.625, "FTF": 3, "Type": "Visa", "Bank Name": "PNC", "Card Name": "Cash Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. checking [Z]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Wells Fargo", "Card Name": "Active Cash", "SUB": 150, "Car Rental CDW": "N", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "Y", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Digital FCU", "Card Name": "Innovations", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "6 States, req. $5 [AA]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "PenFed CU", "Card Name": "Pathfinder Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $500 [J]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "First Tech FCU", "Card Name": "Platinum", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "Y", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. $0 [AB]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "PNC", "Card Name": "Flex", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $500 [Z]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Wings Financial CU", "Card Name": "Visa Signature", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "N", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Wings, $5 [AC]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Alliant CU", "Card Name": "Platinum Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "N", "Membership": "Foster Care to Success, $5, req. checking, e-deposit and $1,000 [C]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Digital FCU", "Card Name": "Platinum", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "6 States, req. $5 [AA]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Langley FCU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AD]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Navy FCU", "Card Name": "cashRewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "N", "Cell Prot.": "Y", "Price Prot.": "N", "Bag Delay": "N", "Membership": "NFCU, $5, req. checking and direct deposit [U]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "PNC", "Card Name": "CashBuilder", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. checking [Z]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "PNC", "Card Name": "Points", "SUB": 50, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. checking [Z]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Santander", "Card Name": "Ultimate Cash Back", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "VyStar CU", "Card Name": "Cash Back", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AE]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "PNC", "Card Name": "Cash Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. checking [Z]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "PNC", "Card Name": "Traveler", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. checking [Z]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "PNC", "Card Name": "Core", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, req. checking [Z]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "SunTrust (now Truist)", "Card Name": "Cash Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "VyStar CU", "Card Name": "Platinum Cash Back", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AE]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Wings Financial CU", "Card Name": "Platinum Rewards", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "N", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Wings, $5 [AC]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "America First CU", "Card Name": "Visa Signature", "SUB": 150, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AF]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "America First CU", "Card Name": "Platinum", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AF]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Security Service FCU", "Card Name": "Power Travel Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AG]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Alliant CU", "Card Name": "Platinum", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Foster Care to Success, $5, req. checking, e-deposit and $1,000 [C]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Golden 1 CU", "Card Name": "Platinum Rewards", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "N", "Purch. Prot.": "N", "Cell Prot.": "N", "Price Prot.": "N", "Bag Delay": "N", "Membership": "Open, $8 [Y]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Randolph-Brooks FCU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AH]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Santander", "Card Name": "Cash Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "SunTrust (now Truist)", "Card Name": "Prime Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "SunTrust (now Truist)", "Card Name": "Cash Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "TDECU", "Card Name": "Infinite", "SUB": 250, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AI]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Wings Financial CU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "N", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Wings, $5 [AC]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "America First CU", "Card Name": "Platinum", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AF]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "America First CU", "Card Name": "Visa Signature", "SUB": 150, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AF]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Langley FCU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AD]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Randolph-Brooks FCU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AH]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Santander", "Card Name": "Ultimate Cash Back", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "VyStar CU", "Card Name": "Cash Back", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AE]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "PNC", "Card Name": "Flex", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $500 [Z]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "SunTrust (now Truist)", "Card Name": "Prime Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "SunTrust (now Truist)", "Card Name": "Cash Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "TDECU", "Card Name": "Infinite", "SUB": 250, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AI]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Wings Financial CU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "N", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Wings, $5 [AC]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "America First CU", "Card Name": "Platinum", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AF]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "America First CU", "Card Name": "Visa Signature", "SUB": 150, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AF]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Langley FCU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AD]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Randolph-Brooks FCU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AH]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Santander", "Card Name": "Ultimate Cash Back", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "VyStar CU", "Card Name": "Cash Back", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AE]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "PNC", "Card Name": "Flex", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $500 [Z]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "SunTrust (now Truist)", "Card Name": "Prime Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "SunTrust (now Truist)", "Card Name": "Cash Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "TDECU", "Card Name": "Infinite", "SUB": 250, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AI]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Wings Financial CU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "N", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Wings, $5 [AC]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "America First CU", "Card Name": "Platinum", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AF]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "America First CU", "Card Name": "Visa Signature", "SUB": 150, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AF]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Langley FCU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AD]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Randolph-Brooks FCU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AH]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "Santander", "Card Name": "Ultimate Cash Back", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "VyStar CU", "Card Name": "Cash Back", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AE]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "PNC", "Card Name": "Flex", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $500 [Z]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "SunTrust (now Truist)", "Card Name": "Prime Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "SunTrust (now Truist)", "Card Name": "Cash Rewards", "SUB": 100, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "TDECU", "Card Name": "Infinite", "SUB": 250, "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $5 [AI]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "Visa", "Bank Name": "Wings Financial CU", "Card Name": "Platinum", "SUB": 200, "Car Rental CDW": "Y", "Travel Accident Ins.": "N", "Trip Canc./ Interr.": "Y", "Ext. Warr.": "N", "Purch. Prot.": "Y", "Cell Prot.": "N", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Wings, $5 [AC]"},
    {"CB": 1.5, "FTF": "No FTF", "Type": "MC", "Bank Name": "America First CU", "Card Name": "Platinum", "SUB": "No SUB", "Car Rental CDW": "Y", "Travel Accident Ins.": "Y", "Trip Canc./ Interr.": "N", "Ext. Warr.": "Y", "Purch. Prot.": "Y", "Cell Prot.": "Y", "Price Prot.": "Y", "Bag Delay": "Y", "Membership": "Open, req. $0 [AF]"},
]
